sudo: false

language: php

services:
  - mongodb

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        EXECUTE_CS_CHECK=true
        INSTALL_PECL_MONGO=true
    - php: 5.6
      env:
        EXECUTE_COVERAGE=true
        INSTALL_PECL_MONGO=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  irc: "irc.freenode.org#apigility-dev"
  email: false

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - if [[ $INSTALL_PECL_MONGO == 'true' ]]; then pecl install -f mongo-1.4.1 || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source --dev

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs --standard=PSR2 --ignore=test/Bootstrap.php src test; fi
